<template>
  <div class="companion-admin app-container">
    <div class="page-heading">
      <div>
        <p class="eyebrow">LINGXI COMPANION · ADMIN</p>
        <h1>{{ pageTitle }}</h1>
        <p class="description">{{ pageDescription }}</p>
      </div>
      <el-button icon="el-icon-refresh" :loading="loading" @click="load">刷新数据</el-button>
    </div>

    <template v-if="moduleName === 'dashboard' || moduleName === 'analytics'">
      <div class="metric-grid">
        <div v-for="metric in metrics" :key="metric.key" class="metric-card">
          <span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.note }}</small>
        </div>
      </div>
      <el-row :gutter="20" class="section-row">
        <el-col :span="15">
          <el-card shadow="never">
            <div slot="header"><span>经营与治理状态</span></div>
            <div v-for="bar in healthBars" :key="bar.label" class="health-row">
              <div><span>{{ bar.label }}</span><b>{{ bar.value }}</b></div>
              <el-progress :percentage="bar.percent" :color="bar.color" :show-text="false" />
            </div>
          </el-card>
        </el-col>
        <el-col :span="9">
          <el-card shadow="never" class="guard-card">
            <div slot="header"><span>安全门禁</span></div>
            <p><i class="el-icon-lock"></i> 私密对话与目标正文默认不可见</p>
            <p><i class="el-icon-key"></i> 高风险操作要求近期认证、原因与工单</p>
            <p><i class="el-icon-document"></i> 配置采用版本、双人复核、灰度与回滚</p>
            <p><i class="el-icon-user"></i> 青少年模式不可在后台手工改为成人</p>
          </el-card>
        </el-col>
      </el-row>
      <el-card v-if="moduleName === 'analytics'" shadow="never" class="section-row">
        <div slot="header" class="card-title"><span>匿名化指标</span><el-tag type="info">按平台/版本/渠道/分类聚合</el-tag></div>
        <el-table :data="metricRows" stripe><el-table-column prop="metricDate" label="日期" width="120"/><el-table-column prop="metricKey" label="指标" min-width="170"/><el-table-column prop="dimensionType" label="维度" width="130"/><el-table-column prop="dimensionValue" label="维度值" min-width="150"/><el-table-column prop="metricValue" label="指标值" width="120"/><el-table-column prop="sampleCount" label="样本数" width="110"/></el-table>
      </el-card>
      <el-card v-if="moduleName === 'analytics'" shadow="never" class="section-row">
        <div slot="header" class="card-title"><span>A/B 实验</span><el-button v-if="hasPermission('experiment:manage')" type="text" @click="createGovernanceResource('EXPERIMENT')">新建实验</el-button></div>
        <resource-table :rows="rows" @retire="retireResource" />
      </el-card>
    </template>

    <template v-else-if="moduleName === 'users'">
      <el-tabs v-model="activeTab" @tab-click="search">
        <el-tab-pane v-if="hasPermission('identity:user:read')" label="用户账号" name="accounts"/>
        <el-tab-pane v-if="hasPermission('identity:risk:manage')" label="登录风险" name="loginRisks"/>
        <el-tab-pane v-if="hasPermission('identity:age-appeal:manage')" label="年龄申诉" name="ageAppeals"/>
        <el-tab-pane v-if="hasPermission('relationship:guardian-dispute:manage')" label="监护争议" name="guardianDisputes"/>
        <el-tab-pane v-if="hasPermission('identity:user:read')" label="隐私请求" name="privacyRequests"/>
      </el-tabs>
      <filter-bar>
        <el-input v-if="activeTab==='accounts'" v-model="filters.keyword" clearable placeholder="用户公开 ID" @keyup.enter.native="search" />
        <el-select v-if="activeTab==='accounts'" v-model="filters.ageBand" clearable placeholder="年龄模式"><el-option label="14—17 岁" value="TEEN"/><el-option label="成人" value="ADULT"/><el-option label="未满 14 岁" value="UNDER_14"/></el-select>
        <el-select v-model="filters.status" clearable placeholder="状态"><el-option v-for="item in userStatuses" :key="item" :label="item" :value="item"/></el-select>
        <el-select v-if="activeTab==='loginRisks'" v-model="filters.riskLevel" clearable placeholder="风险等级"><el-option v-for="item in ['LOW','MEDIUM','HIGH','CRITICAL']" :key="item" :value="item"/></el-select>
        <el-button type="primary" @click="search">查询</el-button>
      </filter-bar>
      <el-table v-if="activeTab==='accounts'" v-loading="loading" :data="rows" stripe>
        <el-table-column prop="publicId" label="用户公开 ID" min-width="210"/>
        <el-table-column prop="ageBand" label="年龄模式" width="120"><template slot-scope="s"><status-tag :value="s.row.ageBand"/></template></el-table-column>
        <el-table-column prop="status" label="账号状态" width="150"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column>
        <el-table-column prop="timezone" label="时区" width="150"/>
        <el-table-column prop="authorizationVersion" label="授权版本" width="100"/>
        <el-table-column prop="createdAt" label="注册时间" min-width="175"/>
        <el-table-column label="操作" fixed="right" width="210"><template slot-scope="s"><el-button type="text" @click="showUserDetail(s.row)">详情</el-button><el-button v-if="hasPermission('identity:user:restrict')" type="text" @click="changeAccountStatus(s.row)">{{ s.row.status === 'RESTRICTED' ? '恢复账号' : '限制账号' }}</el-button></template></el-table-column>
      </el-table>
      <el-table v-else-if="activeTab==='loginRisks'" v-loading="loading" :data="rows" stripe><el-table-column prop="createdAt" label="发现时间" min-width="170"/><el-table-column prop="userId" label="用户 ID" min-width="170"/><el-table-column prop="riskType" label="风险类型" min-width="150"/><el-table-column prop="riskLevel" label="风险等级" width="110"><template slot-scope="s"><status-tag :value="s.row.riskLevel"/></template></el-table-column><el-table-column prop="summary" label="摘要" min-width="240"/><el-table-column prop="status" label="状态" width="110"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column label="操作" width="100"><template slot-scope="s"><el-button type="text" @click="resolveIdentityItem(s.row,'risk')">处置</el-button></template></el-table-column></el-table>
      <el-table v-else-if="activeTab==='ageAppeals'" v-loading="loading" :data="rows" stripe><el-table-column prop="appealNo" label="申诉号" min-width="170"/><el-table-column prop="userId" label="用户 ID" min-width="170"/><el-table-column prop="claimedBirthDate" label="申诉出生日期" width="140"/><el-table-column prop="evidenceRef" label="证据引用" min-width="220" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="110"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column label="操作" width="120"><template slot-scope="s"><el-button v-if="s.row.status==='PENDING'" type="text" @click="resolveIdentityItem(s.row,'appeal')">审核</el-button></template></el-table-column></el-table>
      <el-table v-else-if="activeTab==='guardianDisputes'" v-loading="loading" :data="rows" stripe><el-table-column prop="disputeNo" label="争议号" min-width="170"/><el-table-column prop="teenUserId" label="青少年用户" min-width="170"/><el-table-column prop="guardianUserId" label="监护人" min-width="170"/><el-table-column prop="reason" label="发起原因" min-width="220"/><el-table-column prop="status" label="状态" width="110"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column label="操作" width="100"><template slot-scope="s"><el-button type="text" @click="resolveIdentityItem(s.row,'guardian')">处置</el-button></template></el-table-column></el-table>
      <el-table v-else v-loading="loading" :data="rows" stripe><el-table-column prop="id" label="请求 ID" min-width="170"/><el-table-column prop="userId" label="用户 ID" min-width="170"/><el-table-column prop="type" label="类型" width="150"/><el-table-column prop="status" label="状态" width="120"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="progress" label="进度 %" width="90"/><el-table-column prop="deadline" label="截止时间" min-width="175"/><el-table-column prop="lastError" label="最近错误" min-width="220" show-overflow-tooltip/></el-table>
      <pager :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'templates'">
      <div class="toolbar"><el-select v-model="filters.status" clearable placeholder="模板状态" @change="search"><el-option v-for="item in templateStatuses" :key="item" :label="item" :value="item"/></el-select><el-button type="primary" icon="el-icon-plus" @click="templateDialog=true">新建模板版本</el-button></div>
      <el-table v-loading="loading" :data="rows" stripe>
        <el-table-column prop="templateId" label="模板 ID" width="185"/>
        <el-table-column prop="versionNo" label="版本" width="80"/>
        <el-table-column prop="ageScope" label="适用人群" width="110"/>
        <el-table-column prop="status" label="状态" width="140"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column>
        <el-table-column prop="reviewReason" label="审核说明" min-width="220" show-overflow-tooltip/>
        <el-table-column prop="publishedAt" label="发布时间" min-width="170"/>
        <el-table-column label="操作" width="330" fixed="right"><template slot-scope="s"><el-button v-if="s.row.status==='DRAFT'" type="text" @click="templateAction(s.row,'submit')">提交</el-button><el-button v-if="s.row.status==='REVIEWING'" type="text" @click="reviewTemplateDimensions(s.row)">三维评审</el-button><el-button v-if="s.row.status==='REVIEWING'" type="text" @click="reviewTemplate(s.row,true)">最终发布</el-button><el-button v-if="s.row.status==='REVIEWING'" type="text" class="danger" @click="reviewTemplate(s.row,false)">驳回</el-button><el-button type="text" @click="showTemplateMetrics(s.row)">指标</el-button><el-button v-if="s.row.status==='PUBLISHED'" type="text" class="danger" @click="templateAction(s.row,'retire')">下架</el-button></template></el-table-column>
      </el-table>
    </template>

    <template v-else-if="moduleName === 'commerce'">
      <el-tabs v-model="activeTab" @tab-click="load">
        <el-tab-pane label="商品价格" name="products"/><el-tab-pane label="订单与退款" name="orders"/><el-tab-pane label="订阅" name="subscriptions"/><el-tab-pane label="权益" name="entitlements"/><el-tab-pane v-if="hasPermission('commerce:catalog:manage')" label="促销" name="promotions"/><el-tab-pane v-if="hasPermission('commerce:reconcile:manage')" label="对账" name="reconciliation"/>
      </el-tabs>
      <div class="toolbar"><el-input v-if="activeTab==='orders'" v-model="filters.keyword" clearable placeholder="订单号或用户 ID"/><el-input v-if="activeTab==='entitlements'" v-model="filters.userId" clearable placeholder="用户 ID"/><el-select v-if="!['products','entitlements'].includes(activeTab)" v-model="filters.status" clearable placeholder="状态"/><el-button v-if="activeTab!=='products'" type="primary" @click="search">查询</el-button><el-button v-if="activeTab==='products'&&hasPermission('commerce:catalog:manage')" type="primary" @click="createCommerceResource('product')">新增商品</el-button><el-button v-if="activeTab==='products'&&hasPermission('commerce:catalog:manage')" @click="createCommerceResource('price')">新增价格版本</el-button><el-button v-if="activeTab==='promotions'" type="primary" @click="createCommerceResource('promotion')">新增促销</el-button><el-button v-if="activeTab==='entitlements'&&hasPermission('commerce:entitlement:adjust')" type="primary" @click="adjustEntitlement">调整权益</el-button></div>
      <el-table v-loading="loading" :data="rows" stripe>
        <template v-if="activeTab==='products'"><el-table-column prop="productKey" label="商品标识" min-width="160"/><el-table-column prop="name" label="商品名称" min-width="150"/><el-table-column prop="billingPeriod" label="周期" width="110"/><el-table-column prop="agePolicy" label="年龄策略" width="120"/><el-table-column prop="entitlementKey" label="权益" min-width="150"/><el-table-column label="当前价格" min-width="160"><template slot-scope="s">{{ formatPrice(s.row.prices && s.row.prices[0]) }}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column></template>
        <template v-else-if="activeTab==='orders'"><el-table-column prop="orderNo" label="订单号" min-width="190"/><el-table-column prop="userId" label="用户 ID" min-width="175"/><el-table-column label="金额" width="120"><template slot-scope="s">{{ money(s.row.amountMinor,s.row.currency) }}</template></el-table-column><el-table-column prop="channel" label="渠道" width="100"/><el-table-column prop="status" label="状态" width="150"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="refundedMinor" label="已退款(分)" width="110"/><el-table-column prop="createdAt" label="创建时间" min-width="175"/><el-table-column v-if="hasPermission('commerce.refund.confirm')" label="操作" width="90"><template slot-scope="s"><el-button type="text" @click="refundOrder(s.row)">确认退款</el-button></template></el-table-column></template>
        <template v-else-if="activeTab==='subscriptions'"><el-table-column prop="id" label="订阅 ID" min-width="180"/><el-table-column prop="userId" label="用户 ID" min-width="180"/><el-table-column prop="productId" label="商品 ID" min-width="180"/><el-table-column prop="channel" label="渠道" width="100"/><el-table-column prop="status" label="状态" width="150"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="periodEnd" label="周期结束" min-width="175"/></template>
        <template v-else-if="activeTab==='entitlements'"><el-table-column prop="userId" label="用户 ID" min-width="180"/><el-table-column prop="resourceKey" label="权益资源" min-width="180"/><el-table-column prop="balance" label="余额" width="100"/><el-table-column prop="expiresAt" label="到期时间" min-width="180"/><el-table-column prop="version" label="版本" width="80"/></template>
        <template v-else-if="activeTab==='promotions'"><el-table-column prop="promotionKey" label="促销标识" min-width="160"/><el-table-column prop="name" label="名称" min-width="160"/><el-table-column prop="promotionType" label="类型" width="120"/><el-table-column prop="startsAt" label="开始" min-width="170"/><el-table-column prop="endsAt" label="结束" min-width="170"/><el-table-column prop="status" label="状态" width="100"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column></template>
        <template v-else><el-table-column prop="caseNo" label="对账号" min-width="170"/><el-table-column prop="channel" label="渠道" width="110"/><el-table-column prop="businessId" label="业务 ID" min-width="170"/><el-table-column prop="expectedMinor" label="应有(分)" width="110"/><el-table-column prop="actualMinor" label="实有(分)" width="110"/><el-table-column prop="status" label="状态" width="110"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column label="操作" width="100"><template slot-scope="s"><el-button v-if="s.row.status!=='RESOLVED'" type="text" @click="resolveReconciliation(s.row)">处理</el-button></template></el-table-column></template>
      </el-table>
      <pager v-if="activeTab!=='products'" :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'support'">
      <div class="toolbar"><el-select v-model="filters.status" clearable placeholder="工单状态"/><el-select v-model="filters.category" clearable placeholder="分类"/><el-button type="primary" @click="search">查询</el-button></div>
      <el-table v-loading="loading" :data="rows" stripe>
        <el-table-column prop="ticketNo" label="工单号" min-width="170"/><el-table-column prop="category" label="分类" width="180"/><el-table-column prop="subject" label="主题" min-width="220"/><el-table-column prop="priority" label="优先级" width="100"><template slot-scope="s"><status-tag :value="s.row.priority"/></template></el-table-column><el-table-column prop="status" label="状态" width="130"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="slaDueAt" label="SLA 截止" min-width="175"/><el-table-column prop="followUpAt" label="回访时间" min-width="175"/><el-table-column label="操作" width="180" fixed="right"><template slot-scope="s"><el-button type="text" @click="showTicket(s.row)">详情</el-button><el-button v-if="hasPermission('support:ticket:reply')" type="text" @click="replyTicket(s.row)">回复</el-button><el-button v-if="hasPermission('support.ticket.manage')" type="text" @click="moveTicket(s.row)">流转</el-button></template></el-table-column>
      </el-table><pager :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'aiConfig'">
      <div class="toolbar"><el-input v-model="filters.type" clearable placeholder="配置类型：MODEL_ROUTE / PROMPT / AGENT_POLICY"/><el-select v-model="filters.status" clearable placeholder="状态"/><el-button type="primary" @click="search">查询</el-button><el-button type="primary" icon="el-icon-plus" @click="releaseDialog=true">创建发布</el-button></div>
      <el-table v-loading="loading" :data="rows" stripe>
        <el-table-column prop="releaseKey" label="发布键" min-width="180"/><el-table-column prop="configType" label="配置类型" min-width="150"/><el-table-column prop="versionNo" label="版本" width="80"/><el-table-column prop="contentRef" label="内容引用" min-width="220" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="150"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="createdBy" label="创建人" min-width="170"/><el-table-column label="操作" width="260" fixed="right"><template slot-scope="s"><el-button v-for="action in releaseActions(s.row)" :key="action" type="text" @click="doReleaseAction(s.row,action)">{{ actionLabel(action) }}</el-button></template></el-table-column>
      </el-table><pager :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'safety'">
      <div class="privacy-banner"><i class="el-icon-warning-outline"></i><div><b>最小披露队列</b><p>仅展示处置所需的风险摘要；完整用户内容必须有专项授权并另行审计。</p></div></div>
      <el-tabs v-model="activeTab" @tab-click="search"><el-tab-pane label="处置案件" name="cases"/><el-tab-pane label="值班告警" name="alerts"/></el-tabs>
      <div class="toolbar"><el-select v-model="filters.riskLevel" clearable placeholder="风险等级"/><el-select v-model="filters.status" clearable placeholder="处置状态"/><el-button type="primary" @click="search">查询</el-button></div>
      <el-table v-if="activeTab==='cases'" v-loading="loading" :data="rows" stripe><el-table-column prop="caseNo" label="事件号" min-width="170"/><el-table-column prop="riskCategory" label="风险分类" width="130"/><el-table-column prop="riskLevel" label="风险等级" width="110"><template slot-scope="s"><status-tag :value="s.row.riskLevel"/></template></el-table-column><el-table-column prop="contentExcerpt" label="最小摘要" min-width="260" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="120"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="createdAt" label="发现时间" min-width="175"/><el-table-column label="操作" width="100"><template slot-scope="s"><el-button type="text" @click="handleSafety(s.row)">处置</el-button></template></el-table-column></el-table><el-table v-else v-loading="loading" :data="rows" stripe><el-table-column prop="safetyCaseId" label="案件 ID" min-width="170"/><el-table-column prop="alertChannel" label="告警渠道" width="140"/><el-table-column prop="recipientRef" label="值班对象" min-width="170"/><el-table-column prop="status" label="投递状态" width="120"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="failureReason" label="失败原因" min-width="220"/><el-table-column prop="createdAt" label="创建时间" min-width="175"/><el-table-column label="操作" width="100"><template slot-scope="s"><el-button v-if="['FAILED','SENT','ACKNOWLEDGED'].includes(s.row.status)" type="text" @click="handleSafetyAlert(s.row)">处置</el-button></template></el-table-column></el-table><pager :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'engagement'">
      <div class="privacy-banner"><i class="el-icon-bell"></i><div><b>青少年营销默认关闭</b><p>禁止根据学习成绩、情绪、家庭或目标失败情况进行商业推荐。</p></div></div>
      <div class="toolbar"><el-button type="primary" icon="el-icon-plus" @click="createGovernanceResource('CAMPAIGN')">创建触达活动</el-button></div><resource-table :rows="rows" @retire="retireResource" @runtime="changeResourceRuntime"/><pager :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <template v-else-if="moduleName === 'system'">
      <el-tabs v-model="activeTab" @tab-click="load"><el-tab-pane v-if="hasPermission('identity:admin:manage')" label="管理员" name="admins"/><el-tab-pane v-if="hasPermission('identity:admin:manage')" label="角色权限" name="roles"/><el-tab-pane v-if="hasPermission('audit:read')" label="管理审计" name="audits"/><el-tab-pane v-if="hasPermission('feature:flag:manage')" label="功能开关" name="FEATURE_FLAG"/><el-tab-pane v-if="hasPermission('app:release:manage')" label="客户端版本" name="APP_RELEASE"/><el-tab-pane v-if="hasPermission('compliance:manage')" label="协议与合规" name="COMPLIANCE"/></el-tabs>
      <div v-if="activeTab==='admins'" class="toolbar"><el-button type="primary" icon="el-icon-plus" @click="adminDialog=true">新增管理员</el-button></div>
      <div v-if="activeTab==='roles'" class="toolbar"><el-button type="primary" icon="el-icon-plus" @click="roleDialog=true">新增角色</el-button></div>
      <div v-if="['FEATURE_FLAG','APP_RELEASE','COMPLIANCE'].includes(activeTab)" class="toolbar"><el-button type="primary" icon="el-icon-plus" @click="createGovernanceResource(activeTab)">新增结构化资源</el-button></div>
      <el-table v-if="activeTab==='admins'" v-loading="loading" :data="rows" stripe><el-table-column prop="username" label="登录账号" min-width="150"/><el-table-column prop="displayName" label="显示名称" min-width="150"/><el-table-column label="角色" min-width="220"><template slot-scope="s"><el-tag v-for="r in s.row.roles" :key="r.id" size="mini" class="role-tag">{{ r.name }}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="100"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="lastLoginAt" label="最近登录" min-width="175"/><el-table-column label="操作" width="230" fixed="right"><template slot-scope="s"><el-button type="text" @click="editAdminRoles(s.row)">分配角色</el-button><el-button type="text" @click="resetAdminPwd(s.row)">重置密码</el-button><el-button type="text" :class="s.row.status==='ACTIVE'?'danger':''" @click="toggleAdmin(s.row)">{{ s.row.status==='ACTIVE'?'停用':'启用' }}</el-button></template></el-table-column></el-table>
      <el-table v-else-if="activeTab==='roles'" v-loading="loading" :data="rows" stripe><el-table-column prop="roleKey" label="角色标识" min-width="180"/><el-table-column prop="name" label="角色名称" min-width="160"/><el-table-column prop="status" label="状态" width="100"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column label="权限" min-width="360"><template slot-scope="s"><span class="permission-count">{{ s.row.permissions.length }} 项</span><el-tag v-for="p in s.row.permissions.slice(0,4)" :key="p.id" size="mini" class="role-tag">{{ p.name }}</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template slot-scope="s"><el-button v-if="s.row.roleKey!=='SUPER_ADMIN'" type="text" @click="editRolePermissions(s.row)">配置权限</el-button><el-tag v-else size="mini" type="warning">系统保护</el-tag></template></el-table-column></el-table>
      <el-table v-else-if="activeTab==='audits'" v-loading="loading" :data="rows" stripe><el-table-column prop="createdAt" label="时间" min-width="175"/><el-table-column prop="adminId" label="管理员" min-width="175"/><el-table-column prop="action" label="动作" min-width="170"/><el-table-column prop="objectType" label="对象类型" width="140"/><el-table-column prop="objectId" label="对象 ID" min-width="150"/><el-table-column prop="reason" label="原因" min-width="220" show-overflow-tooltip/><el-table-column prop="ticketNo" label="工单号" min-width="140"/><el-table-column prop="result" label="结果" width="100"><template slot-scope="s"><status-tag :value="s.row.result"/></template></el-table-column></el-table>
      <resource-table v-else :rows="rows" @retire="retireResource" @runtime="changeResourceRuntime"/><pager v-if="!['admins','roles'].includes(activeTab)" :total="total" :page.sync="page" :size.sync="pageSize" @change="load"/>
    </template>

    <el-dialog title="新建模板版本" :visible.sync="templateDialog" width="560px"><el-form label-width="100px"><el-form-item label="模板标识"><el-input v-model="templateForm.templateKey"/></el-form-item><el-form-item label="模板名称"><el-input v-model="templateForm.name"/></el-form-item><el-form-item label="版本号"><el-input-number v-model="templateForm.versionNo" :min="1"/></el-form-item><el-form-item label="适用人群"><el-select v-model="templateForm.ageScope"><el-option label="全部" value="ALL"/><el-option label="青少年" value="TEEN"/><el-option label="成人" value="ADULT"/></el-select></el-form-item><el-form-item label="内容快照"><el-input v-model="templateForm.contentSnapshot" type="textarea" :rows="8" placeholder="JSON 内容快照"/></el-form-item></el-form><span slot="footer"><el-button @click="templateDialog=false">取消</el-button><el-button type="primary" @click="saveTemplate">保存草稿</el-button></span></el-dialog>
    <el-dialog :title="resourceEditor.title" :visible.sync="resourceEditor.visible" width="720px">
      <el-alert title="按结构化业务字段保存；规则类字段单独校验 JSON，高风险提交要求重新认证、原因和工单号。" type="info" :closable="false"/>
      <el-form label-width="120px" class="dialog-form">
        <el-form-item v-for="field in editorFields()" :key="field.key" :label="field.label" :required="field.required">
          <el-select v-if="field.type==='select'" v-model="resourceEditor.form[field.key]" style="width:100%">
            <el-option v-for="option in field.options" :key="option" :label="option" :value="option"/>
          </el-select>
          <el-input-number v-else-if="field.type==='number'" v-model="resourceEditor.form[field.key]" :min="field.min===undefined?0:field.min" :precision="0" :disabled="field.readonly" style="width:100%"/>
          <el-switch v-else-if="field.type==='boolean'" v-model="resourceEditor.form[field.key]"/>
          <el-date-picker v-else-if="field.type==='datetime'" v-model="resourceEditor.form[field.key]" type="datetime" value-format="yyyy-MM-dd'T'HH:mm:ss" style="width:100%"/>
          <el-input v-else v-model="resourceEditor.form[field.key]" :type="field.type==='textarea'||field.type==='json'?'textarea':'text'" :rows="field.type==='json'?5:3" :disabled="field.readonly" :placeholder="field.type==='json'?'请输入合法 JSON':''"/>
        </el-form-item>
      </el-form>
      <span slot="footer"><el-button @click="resourceEditor.visible=false">取消</el-button><el-button type="primary" @click="saveStructuredResource">校验并保存</el-button></span>
    </el-dialog>
    <el-dialog title="创建版本化配置发布" :visible.sync="releaseDialog" width="600px"><el-alert title="页面不接收生产密钥；contentRef 仅填写安全配置引用。" type="warning" :closable="false"/><el-form label-width="110px" class="dialog-form"><el-form-item label="发布键"><el-input v-model="releaseForm.releaseKey"/></el-form-item><el-form-item label="配置类型"><el-input v-model="releaseForm.configType"/></el-form-item><el-form-item label="版本号"><el-input-number v-model="releaseForm.versionNo" :min="1"/></el-form-item><el-form-item label="内容引用"><el-input v-model="releaseForm.contentRef"/></el-form-item><el-form-item label="内容摘要"><el-input v-model="releaseForm.contentDigest" maxlength="64"/></el-form-item><el-form-item label="灰度规则"><el-input v-model="releaseForm.grayRule" type="textarea" placeholder="JSON，可留空"/></el-form-item><el-form-item label="操作原因"><el-input v-model="riskContext.reason"/></el-form-item><el-form-item label="工单号"><el-input v-model="riskContext.ticketNo"/></el-form-item></el-form><span slot="footer"><el-button @click="releaseDialog=false">取消</el-button><el-button type="primary" @click="saveRelease">创建草稿</el-button></span></el-dialog>
    <el-dialog title="新增管理员" :visible.sync="adminDialog" width="560px"><el-form label-width="100px"><el-form-item label="登录账号"><el-input v-model="adminForm.username"/></el-form-item><el-form-item label="显示名称"><el-input v-model="adminForm.displayName"/></el-form-item><el-form-item label="初始密码"><el-input v-model="adminForm.password" type="password" show-password placeholder="至少 12 位"/></el-form-item><el-form-item label="角色"><el-checkbox-group v-model="adminForm.roleIds"><el-checkbox v-for="r in adminRoleOptions" :key="r.id" :label="r.id">{{ r.name }}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="操作原因"><el-input v-model="riskContext.reason"/></el-form-item><el-form-item label="工单号"><el-input v-model="riskContext.ticketNo"/></el-form-item></el-form><span slot="footer"><el-button @click="adminDialog=false">取消</el-button><el-button type="primary" @click="saveAdmin">创建账号</el-button></span></el-dialog>
    <el-dialog :title="selectionTitle" :visible.sync="selectionDialog" width="680px"><el-checkbox-group v-model="selectedIds" class="permission-grid"><el-checkbox v-for="item in selectionOptions" :key="item.id" :label="item.id">{{ item.name }}<small>{{ item.permissionKey || item.roleKey }}</small></el-checkbox></el-checkbox-group><el-form label-width="90px" class="dialog-form"><el-form-item label="操作原因"><el-input v-model="riskContext.reason"/></el-form-item><el-form-item label="工单号"><el-input v-model="riskContext.ticketNo"/></el-form-item></el-form><span slot="footer"><el-button @click="selectionDialog=false">取消</el-button><el-button type="primary" @click="saveSelection">保存</el-button></span></el-dialog>
    <el-dialog title="新增角色" :visible.sync="roleDialog" width="680px"><el-form label-width="100px"><el-form-item label="角色标识"><el-input v-model="roleForm.roleKey" placeholder="如 CONTENT_REVIEWER"/></el-form-item><el-form-item label="角色名称"><el-input v-model="roleForm.name"/></el-form-item><el-form-item label="权限"><el-checkbox-group v-model="roleForm.permissionIds" class="permission-grid"><el-checkbox v-for="p in adminPermissionOptions" :key="p.id" :label="p.id">{{ p.name }}<small>{{ p.permissionKey }}</small></el-checkbox></el-checkbox-group></el-form-item><el-form-item label="操作原因"><el-input v-model="riskContext.reason"/></el-form-item><el-form-item label="工单号"><el-input v-model="riskContext.ticketNo"/></el-form-item></el-form><span slot="footer"><el-button @click="roleDialog=false">取消</el-button><el-button type="primary" @click="saveRole">创建角色</el-button></span></el-dialog>
  </div>
</template>

<script>
import * as api from '@/api/companionAdmin'

const StatusTag = { props: ['value'], render(h) { const danger = ['CRITICAL','HIGH','FAILED','RESTRICTED','REJECTED'].includes(this.value); const success = ['ACTIVE','ACTIVE_ADULT','ACTIVE_TEEN','PAID','PUBLISHED','SUCCESS','RESOLVED'].includes(this.value); return h('el-tag', { props: { size: 'mini', type: danger ? 'danger' : success ? 'success' : 'info' } }, this.value || '-') } }
const Pager = { props: ['total','page','size'], render(h) { return h('el-pagination', { class: 'pager', props: { total: this.total, currentPage: this.page, pageSize: this.size, pageSizes: [10,20,50,100], layout: 'total, sizes, prev, pager, next' }, on: { 'update:currentPage': v => this.$emit('update:page', v), 'update:pageSize': v => this.$emit('update:size', v), 'current-change': () => this.$emit('change'), 'size-change': () => this.$emit('change') } }) } }
const FilterBar = { render(h) { return h('div', { class: 'toolbar filter-bar' }, this.$slots.default) } }
const ResourceTable = { props: ['rows'], components: { StatusTag }, template: '<el-table :data="rows" stripe><el-table-column prop="resourceType" label="类型" width="140"/><el-table-column prop="resourceKey" label="标识" min-width="180"/><el-table-column prop="name" label="名称/版本" min-width="170"/><el-table-column prop="status" label="状态" width="120"><template slot-scope="s"><status-tag :value="s.row.status"/></template></el-table-column><el-table-column prop="detailJson" label="规则/安全引用" min-width="260" show-overflow-tooltip/><el-table-column prop="updatedAt" label="更新时间" min-width="175"/><el-table-column label="操作" width="160"><template slot-scope="s"><el-button v-if="s.row.status!==\'RETIRED\'" type="text" @click="$emit(\'runtime\',s.row)">运行状态</el-button><el-button v-if="[\'DRAFT\',\'COMPLETED\',\'CANCELLED\'].includes(s.row.status)" type="text" class="danger" @click="$emit(\'retire\',s.row)">退役</el-button></template></el-table-column></el-table>' }

export default {
  name: 'CompanionAdmin', components: { StatusTag, Pager, FilterBar, ResourceTable },
  data() { return { loading: false, rows: [], metricRows: [], total: 0, page: 1, pageSize: 20, activeTab: 'products', filters: {}, dashboardData: {}, templateDialog: false, releaseDialog: false, adminDialog: false, roleDialog: false, selectionDialog: false, selectionMode: '', selectionTarget: null, selectionTitle: '', selectionOptions: [], selectedIds: [], adminRoleOptions: [], adminPermissionOptions: [], templateForm: { templateKey: '', name: '', versionNo: 1, ageScope: 'ALL', contentSnapshot: '{}' }, releaseForm: { releaseKey: '', configType: 'MODEL_ROUTE', versionNo: 1, contentRef: '', contentDigest: '', grayRule: '' }, resourceEditor: { visible: false, type: '', title: '', form: {} }, adminForm: { username: '', displayName: '', password: '', roleIds: [] }, roleForm: { roleKey: '', name: '', permissionIds: [] }, riskContext: { reason: '', ticketNo: '' }, userStatuses: ['OPEN','PENDING','REVIEWING','RESOLVED','DISMISSED','APPROVED','REJECTED','PENDING_GUARDIAN','ACTIVE_TEEN','ACTIVE_ADULT','RESTRICTED','AGE_TRANSITION','CLOSING','CLOSED'], templateStatuses: ['DRAFT','REVIEWING','PUBLISHED','REJECTED','RETIRED'] } },
  computed: {
    moduleName() { return this.$route.meta.module },
    pageTitle() { return this.$route.meta.title },
    pageDescription() { return ({ dashboard:'关键业务、风险、成本与发布状态的统一入口。', users:'账号、年龄模式、会员事实与安全限制，默认不展示私人内容。', templates:'目标模板的草稿、审核、发布、下架与版本治理。', aiConfig:'模型路由、Prompt、Agent 策略和安全规则的版本化发布。', safety:'风险命中、人工复核和应急处置的最小披露队列。', engagement:'Push 模板、人群、频控、免打扰与触达效果。', commerce:'商品价格、订单、订阅、退款和权益账本。', support:'账号、支付、AI、隐私、安全与伙伴投诉的 SLA 工单。', analytics:'匿名化漏斗、留存、转化、质量、成本与实验。', system:'功能开关、App 版本、协议、合规材料和不可抵赖审计。' })[this.moduleName] || '' },
    metrics() { const d=this.dashboardData; return [{key:'users',label:'用户总数',value:d.users||0,note:`青少年 ${d.teenUsers||0}`},{key:'orders',label:'订单总数',value:d.orders||0,note:`已支付 ${d.paidOrders||0}`},{key:'revenue',label:'累计收入',value:this.money(d.revenueMinor||0,'CNY'),note:`活跃订阅 ${d.activeSubscriptions||0}`},{key:'tickets',label:'待处理工单',value:d.openTickets||0,note:'按 SLA 优先级处理'},{key:'risks',label:'高风险事件',value:d.highRiskCases||0,note:'需值班复核'},{key:'releases',label:'待发布配置',value:d.pendingReleases||0,note:`今日审计 ${d.auditActionsToday||0}`}] },
    healthBars() { const d=this.dashboardData; return [{label:'订单支付完成',value:d.paidOrders||0,percent:this.percent(d.paidOrders,d.orders),color:'#16a34a'},{label:'客服队列健康',value:d.openTickets||0,percent:Math.max(5,100-Math.min(95,(d.openTickets||0)*4)),color:'#2563eb'},{label:'安全事件收敛',value:d.highRiskCases||0,percent:Math.max(5,100-Math.min(95,(d.highRiskCases||0)*10)),color:'#dc2626'}] }
  },
  watch: { '$route.path': { immediate: true, handler() { this.page=1; this.filters={}; this.activeTab=this.initialTab(); this.load() } } },
  methods: {
    hasPermission(key){const p=this.$store.getters.permissions||[];return p.includes('*')||p.includes(key)},
    initialTab(){if(this.moduleName==='users'){if(this.hasPermission('identity:user:read'))return'accounts';if(this.hasPermission('identity:risk:manage'))return'loginRisks';if(this.hasPermission('identity:age-appeal:manage'))return'ageAppeals';return'guardianDisputes'}if(this.moduleName==='system'){if(this.hasPermission('identity:admin:manage'))return'admins';if(this.hasPermission('audit:read'))return'audits';if(this.hasPermission('feature:flag:manage'))return'FEATURE_FLAG';if(this.hasPermission('app:release:manage'))return'APP_RELEASE';return'COMPLIANCE'}if(this.moduleName==='safety')return'cases';return'products'},
    async load() { this.loading=true; try { let res; const p={...this.filters,page:this.page,pageSize:this.pageSize}; switch(this.moduleName){ case 'dashboard': res=await api.dashboard();this.dashboardData=res.data;this.rows=[];break; case 'analytics': if(this.hasPermission('dashboard:read'))this.dashboardData=(await api.dashboard()).data;this.metricRows=(await api.analyticsMetrics(this.filters)).data||[];await this.loadGovernanceResources('EXPERIMENT',p);break; case 'users': res=await this.loadIdentity(p);this.pageData(res);break; case 'templates': res=await api.templates(this.filters);this.rows=res.data||[];this.total=this.rows.length;break; case 'commerce': res=await this.loadCommerce(p);this.consumeCommerce(res);break; case 'support': res=await api.tickets(p);this.pageData(res);break; case 'aiConfig': res=await api.releases(p);this.pageData(res);break; case 'safety': res=this.activeTab==='alerts'?await api.safetyAlerts(p):await api.safetyCases(p);this.pageData(res);break; case 'engagement': await this.loadGovernanceResources('CAMPAIGN',p);break; case 'system': if(this.activeTab==='admins'||this.activeTab==='roles'){const all=await Promise.all([api.adminAccounts(),api.adminRoles(),api.adminPermissions()]);this.adminRoleOptions=all[1].data||[];this.adminPermissionOptions=all[2].data||[];this.rows=this.activeTab==='admins'?(all[0].data||[]):this.adminRoleOptions;this.total=this.rows.length}else if(this.activeTab==='audits'){res=await api.audits(p);this.pageData(res)}else await this.loadGovernanceResources(this.activeTab,p);break } } finally { this.loading=false } },
    async loadGovernanceResources(type,p){const res=await api.governanceResources({...p,resourceType:type});this.pageData(res)},
    async loadIdentity(p){if(this.activeTab==='accounts')return api.users(p);if(this.activeTab==='loginRisks')return api.loginRisks(p);if(this.activeTab==='ageAppeals')return api.ageAppeals(p);if(this.activeTab==='guardianDisputes')return api.guardianDisputes(p);return api.privacyRequests(p)},
    async loadCommerce(p){if(this.activeTab==='products')return api.products();if(this.activeTab==='orders')return api.orders(p);if(this.activeTab==='subscriptions')return api.subscriptions(p);if(this.activeTab==='entitlements')return api.entitlements({...p,userId:p.userId||undefined});if(this.activeTab==='promotions')return api.promotions(p);return api.reconciliationCases(p)},
    consumeCommerce(res){if(this.activeTab==='products'){this.rows=res.data||[];this.total=this.rows.length}else this.pageData(res)},
    pageData(res){const d=res.data||{};this.rows=d.items||[];this.total=Number(d.total||0)}, search(){this.page=1;this.load()},
    async reauthenticate(title){const password=await this.$prompt('请重新输入管理员密码完成近期认证',title,{inputType:'password',inputValidator:v=>!!v||'密码不能为空'});await api.adminReauthenticate(password.value)},
    async riskPrompt(title){await this.reauthenticate(title);const reason=await this.$prompt('请输入具体操作原因',title,{inputValidator:v=>!!(v&&v.trim())||'原因不能为空'});const ticket=await this.$prompt('请输入关联工单号',title,{inputValidator:v=>!!(v&&v.trim())||'工单号不能为空'});return{reason:reason.value,ticketNo:ticket.value}},
    async showUserDetail(row){const d=(await api.userDetail(row.id)).data||{};await this.$alert(JSON.stringify(d,null,2),'用户治理详情',{customClass:'json-message'})},
    async resolveIdentityItem(row,type){try{const resolution=(await this.$prompt('请输入处置结论','治理处置',{inputValidator:v=>!!(v&&v.trim())||'结论不能为空'})).value;const c=await this.riskPrompt('治理处置');if(type==='risk'){const status=(await this.$prompt('目标状态：REVIEWING / RESOLVED / DISMISSED','登录风险')).value;await api.resolveLoginRisk(row.id,{status,resolution,expectedVersion:row.version},c.reason,c.ticketNo)}else if(type==='appeal'){const decision=(await this.$prompt('输入 APPROVED 或 REJECTED','年龄申诉')).value;await api.reviewAgeAppeal(row.id,{approved:decision==='APPROVED',resolution,expectedVersion:row.version},c.reason,c.ticketNo)}else{const status=(await this.$prompt('目标状态：REVIEWING / RESOLVED / DISMISSED','监护争议')).value;await api.resolveGuardianDispute(row.id,{status,resolution,expectedVersion:row.version},c.reason,c.ticketNo)}this.$message.success('治理记录已更新');this.load()}catch(e){this.notifyError(e)}},
    async changeAccountStatus(row){try{const c=await this.riskPrompt(row.status==='RESTRICTED'?'恢复账号':'限制账号');let target='RESTRICTED';if(row.status==='RESTRICTED')target=row.ageBand==='TEEN'?'ACTIVE_TEEN':row.ageBand==='ADULT'?'ACTIVE_ADULT':'PENDING_GUARDIAN';await api.changeUserStatus(row.id,{status:target,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('账号状态已更新，原会话已撤销');this.load()}catch(e){this.notifyError(e)}},
    async saveTemplate(){await api.createTemplate(this.templateForm);this.templateDialog=false;this.$message.success('模板草稿已创建');this.load()},
    async templateAction(row,action){if(action==='retire'){const c=await this.riskPrompt('下架模板');await api.templateAction(row.id,action,{expectedVersion:row.version},c.reason,c.ticketNo)}else await api.templateAction(row.id,action,{expectedVersion:row.version});this.$message.success('模板状态已更新');this.load()},
    async reviewTemplate(row,approved){let reason='审核通过';if(!approved){const r=await this.$prompt('请输入驳回原因','模板审核');reason=r.value}const c=await this.riskPrompt('模板审核');await api.templateAction(row.id,'review',{approved,reason,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('审核完成');this.load()},
    async reviewTemplateDimensions(row){try{const existing=(await api.templateReviews(row.id)).data||[];const c=await this.riskPrompt('模板三维评审');const templateVersion=Number(row.version);for(const dimension of ['SAFETY','FEASIBILITY','QUALITY']){const old=existing.find(x=>x.dimension===dimension&&Number(x.templateVersion)===templateVersion);const decision=(await this.$prompt(`${dimension} 评审：APPROVED / REJECTED`,'模板三维评审',{inputValue:old?old.decision:'APPROVED'})).value;const comment=(await this.$prompt(`${dimension} 评审说明`,'模板三维评审',{inputValue:old?old.comment:''})).value;await api.saveTemplateReview(row.id,{dimension,decision,comment,expectedVersion:row.version},c.reason,c.ticketNo)}this.$message.success('三维评审已保存');this.load()}catch(e){this.notifyError(e)}},
    async showTemplateMetrics(row){const result=await api.templateMetrics(row.id,{});await this.$alert(JSON.stringify(result.data||[],null,2),'模板近 30 日指标')},
    editorFields(){
      const f=(key,label,type='text',required=true,extra={})=>({key,label,type,required,...extra})
      const version=[f('status','状态','text',true,{readonly:true}),f('expectedVersion','期望版本','number',true,{min:0,readonly:true})]
      const schemas={
        CAMPAIGN:[f('campaignKey','活动标识'),f('name','活动名称'),f('channel','触达渠道','select',true,{options:['INBOX','PUSH','EMAIL','SMS']}),f('audienceRule','受众规则','json'),f('templateContent','消息内容','textarea'),f('frequencyRule','频控规则','json'),f('teenMarketingEnabled','青少年营销','boolean',false),f('scheduledAt','计划时间','datetime',false),...version],
        APP_RELEASE:[f('platform','客户端','select',true,{options:['PC_WEB','HARMONY']}),f('versionName','版本名称'),f('versionCode','版本代码','number',true,{min:1}),f('minimumVersionCode','最低版本代码','number',true,{min:1}),f('forceUpgrade','强制升级','boolean',false),f('grayRule','灰度规则','json',false),f('releaseNotes','发布说明','textarea'),...version],
        COMPLIANCE:[f('documentType','文档类型'),f('versionNo','文档版本'),f('title','标题'),f('contentRef','内容引用'),f('contentDigest','SHA-256 摘要'),f('effectiveAt','生效时间','datetime',false),...version],
        FEATURE_FLAG:[f('flagKey','开关标识'),f('mandatoryPolicy','强制安全策略','boolean',false),...version],
        EXPERIMENT:[f('experimentKey','实验标识'),f('hypothesis','实验假设','textarea'),f('audienceRule','受众规则','json'),f('metricsJson','指标定义','json'),...version],
        'commerce:product':[f('productKey','商品标识'),f('name','商品名称'),f('scene','场景'),f('billingPeriod','计费周期','select',true,{options:['ONE_TIME','MONTHLY','YEARLY']}),f('agePolicy','年龄策略','select',true,{options:['ADULT_ONLY','ALL','TEEN_ALLOWED']}),f('entitlementKey','权益标识'),f('entitlementAmount','权益数量','number',true,{min:1}),...version],
        'commerce:price':[f('productId','商品 ID','number',true,{min:1}),f('versionNo','价格版本','number',true,{min:1}),f('amountMinor','金额（分）','number',true,{min:1}),f('currency','币种'),...version],
        'commerce:promotion':[f('promotionKey','促销标识'),f('name','促销名称'),f('promotionType','促销类型'),f('ruleJson','优惠规则','json'),f('audienceRule','受众规则','json'),f('startsAt','开始时间','datetime'),f('endsAt','结束时间','datetime'),...version],
        'commerce:refund':[f('channel','支付渠道'),f('refundTransactionId','渠道退款单号'),f('orderNo','订单号'),f('amountMinor','退款金额（分）','number',true,{min:1}),f('refundReason','退款原因','textarea')],
        'commerce:entitlement':[f('userId','用户 ID','number',true,{min:1}),f('resourceKey','权益标识'),f('delta','调整数量','number',true,{min:-999999999}),f('expiresAt','到期时间','datetime',false),f('commandId','幂等命令号')],
        'commerce:reconciliation':[f('resolution','处理结论','textarea'),f('expectedVersion','期望版本','number',true,{min:0})]
      }
      return schemas[this.resourceEditor.type]||[]
    },
    openEditor(type,title,payload){this.resourceEditor={visible:true,type,title,form:this.normalizeLongFields({...payload})}},
    // 服务端 64 位整型统一序列化为字符串（见 lingxi-server JacksonLongAsStringConfiguration），
    // el-input-number 需要数字，因此编辑既有资源时把长整型字段还原为 Number。
    normalizeLongFields(form){for(const key of ['id','expectedVersion','amountMinor','versionCode','minimumVersionCode','entitlementAmount','productId','userId','delta','currentReleaseId']){if(form[key]!==null&&form[key]!==undefined&&form[key]!==''){form[key]=Number(form[key])}}return form},
    createGovernanceResource(type){const now=new Date(Date.now()+3600000).toISOString().slice(0,19);const defaults={CAMPAIGN:{id:0,campaignKey:`campaign-${Date.now()}`,name:'新触达活动',channel:'PUSH',audienceRule:'{"ageBands":["ADULT"]}',templateContent:'',frequencyRule:'{"dailyLimit":1,"respectDnd":true}',teenMarketingEnabled:false,scheduledAt:now,status:'DRAFT',expectedVersion:0},APP_RELEASE:{id:0,platform:'HARMONY',versionName:'1.0.0',versionCode:10000,minimumVersionCode:10000,forceUpgrade:false,grayRule:'{}',releaseNotes:'',status:'DRAFT',expectedVersion:0},COMPLIANCE:{id:0,documentType:'PRIVACY_POLICY',versionNo:'1.0.0',title:'隐私政策',contentRef:'',contentDigest:'0000000000000000000000000000000000000000000000000000000000000000',effectiveAt:now,status:'DRAFT',expectedVersion:0},FEATURE_FLAG:{id:0,flagKey:`flag-${Date.now()}`,currentReleaseId:null,mandatoryPolicy:false,status:'DRAFT',expectedVersion:0},EXPERIMENT:{id:0,experimentKey:`experiment-${Date.now()}`,hypothesis:'',audienceRule:'{}',metricsJson:'{}',currentReleaseId:null,status:'DRAFT',expectedVersion:0}};this.openEditor(type,`新增 ${type}`,defaults[type])},
    createCommerceResource(type){const now=new Date().toISOString().slice(0,19);const later=new Date(Date.now()+86400000*30).toISOString().slice(0,19);const defaults={product:{id:0,productKey:`product-${Date.now()}`,name:'新商品',scene:'ALL',billingPeriod:'ONE_TIME',agePolicy:'ADULT_ONLY',entitlementKey:'AGENT_CREDIT',entitlementAmount:1,status:'DRAFT',expectedVersion:0},price:{id:0,productId:0,versionNo:1,amountMinor:100,currency:'CNY',status:'DRAFT',expectedVersion:0},promotion:{id:0,promotionKey:`promotion-${Date.now()}`,name:'新促销',promotionType:'DISCOUNT',ruleJson:'{}',audienceRule:'{}',startsAt:now,endsAt:later,status:'DRAFT',expectedVersion:0}};this.openEditor(`commerce:${type}`,`新增${type}`,defaults[type])},
    refundOrder(row){this.openEditor('commerce:refund','确认退款',{channel:row.channel,refundTransactionId:'',orderNo:row.orderNo,amountMinor:row.amountMinor-row.refundedMinor,refundReason:''})},
    adjustEntitlement(){this.openEditor('commerce:entitlement','调整权益',{userId:Number(this.filters.userId)||0,resourceKey:'AGENT_CREDIT',delta:1,expiresAt:null,commandId:`ADMIN-${Date.now()}`})},
    resolveReconciliation(row){this.openEditor('commerce:reconciliation','处理对账差异',{id:row.id,resolution:'',expectedVersion:row.version})},
    async saveStructuredResource(){const body={...this.resourceEditor.form};for(const field of this.editorFields()){const value=body[field.key];if(field.required&&(value===null||value===undefined||String(value).trim()==='')){this.$message.error(`${field.label}不能为空`);return}if(field.type==='json'&&value){try{JSON.parse(value)}catch(e){this.$message.error(`${field.label}不是合法 JSON`);return}}}try{const c=await this.riskPrompt(this.resourceEditor.title);const t=this.resourceEditor.type;if(t==='CAMPAIGN')await api.saveCampaign(body,c.reason,c.ticketNo);else if(t==='APP_RELEASE')await api.saveAppRelease(body,c.reason,c.ticketNo);else if(t==='COMPLIANCE')await api.saveComplianceDocument(body,c.reason,c.ticketNo);else if(t==='FEATURE_FLAG')await api.saveFeatureFlag(body,c.reason,c.ticketNo);else if(t==='EXPERIMENT')await api.saveExperiment(body,c.reason,c.ticketNo);else if(t==='commerce:product')await api.saveProduct(body,c.reason,c.ticketNo);else if(t==='commerce:price')await api.savePrice(body,c.reason,c.ticketNo);else if(t==='commerce:promotion')await api.savePromotion(body,c.reason,c.ticketNo);else if(t==='commerce:refund')await api.confirmRefund(body,c.reason,c.ticketNo);else if(t==='commerce:entitlement')await api.adjustEntitlement(body,c.reason,c.ticketNo);else if(t==='commerce:reconciliation')await api.resolveReconciliation(body.id,{resolution:body.resolution,expectedVersion:body.expectedVersion},c.reason,c.ticketNo);this.resourceEditor.visible=false;this.$message.success('业务资源已保存');this.load()}catch(e){this.notifyError(e)}},
    async retireResource(row){try{const c=await this.riskPrompt('退役治理资源');await api.retireGovernanceResource(row.resourceType,row.id,row.version,c.reason,c.ticketNo);this.$message.success('资源已退役');this.load()}catch(e){this.notifyError(e)}},
    async changeResourceRuntime(row){try{const requiredRef=`governance://${row.resourceType}/${row.id}`;const release=await this.$prompt(`请输入已全量发布的发布单 ID；该发布单内容引用必须为 ${requiredRef}`,'变更运行状态',{inputValidator:v=>/^\d+$/.test(v)||'请输入数字 ID'});const defaults={CAMPAIGN:'RUNNING',APP_RELEASE:'PUBLISHED',COMPLIANCE:'PUBLISHED',FEATURE_FLAG:'ACTIVE',EXPERIMENT:'RUNNING'};const status=await this.$prompt('请输入目标运行状态','变更运行状态',{inputValue:defaults[row.resourceType]||''});const c=await this.riskPrompt('变更运行状态');await api.changeGovernanceRuntimeStatus(row.resourceType,row.id,{releaseId:Number(release.value),targetStatus:status.value,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('运行状态已更新');this.load()}catch(e){this.notifyError(e)}},
    async showTicket(row){const d=(await api.ticketDetail(row.id)).data||{};await this.$alert(JSON.stringify(d,null,2),`工单 ${row.ticketNo}`)},
    async replyTicket(row){try{const content=(await this.$prompt('请输入回复内容','回复工单',{inputType:'textarea',inputValidator:v=>!!(v&&v.trim())||'回复不能为空'})).value;const c=await this.riskPrompt('回复工单');await api.replyTicket(row.id,{content,internalNote:false,followUpAt:null},c.reason,c.ticketNo);this.$message.success('回复已保存');this.load()}catch(e){this.notifyError(e)}},
    async moveTicket(row){try{const s=await this.$prompt('目标状态：IN_PROGRESS / WAITING_USER / RESOLVED / CLOSED','工单流转');const c=await this.riskPrompt('工单流转');await api.transitionTicket(row.id,{status:s.value,assigneeAdminId:this.$store.getters.id,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('工单已流转');this.load()}catch(e){this.notifyError(e)}},
    async handleSafety(row){try{const s=await this.$prompt('目标状态：REVIEWING / ESCALATED / RESOLVED / CLOSED','安全事件处置');let resolution='';if(['RESOLVED','CLOSED'].includes(s.value)){const r=await this.$prompt('请输入处置结论','安全事件处置');resolution=r.value}const c=await this.riskPrompt('安全事件处置');await api.transitionSafetyCase(row.id,{status:s.value,resolution,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('安全事件状态已更新');this.load()}catch(e){this.notifyError(e)}},
    async handleSafetyAlert(row){try{const choices=row.status==='FAILED'?'PENDING':'ACKNOWLEDGED / RESOLVED';const target=await this.$prompt(`目标状态：${choices}`,'安全告警处置');const c=await this.riskPrompt('安全告警处置');await api.transitionSafetyAlert(row.id,{status:target.value,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('告警状态已更新');this.load()}catch(e){this.notifyError(e)}},
    async saveRelease(){try{if(!this.riskContext.reason.trim()||!this.riskContext.ticketNo.trim()){this.$message.error('请填写操作原因和工单号');return}await this.reauthenticate('创建配置发布');await api.createRelease({...this.releaseForm,grayRule:this.releaseForm.grayRule||null},this.riskContext.reason,this.riskContext.ticketNo);this.releaseDialog=false;this.riskContext={reason:'',ticketNo:''};this.$message.success('配置发布草稿已创建');this.load()}catch(e){this.notifyError(e)}},
    openRelease(type){this.releaseForm={releaseKey:`${type.toLowerCase()}-${Date.now()}`,configType:type,versionNo:1,contentRef:'',contentDigest:'',grayRule:''};this.releaseDialog=true},
    releaseActions(row){let actions;if(row.status==='PENDING_APPROVAL')actions=row.approvedBy?['gray']:['approve'];else actions=({DRAFT:['validate'],FAILED:['validate'],GRAY:['publish','rollback'],PUBLISHED:['rollback']})[row.status]||[];const permission={validate:'config.release.validate',approve:'config.release.approve',gray:'config.release.publish',publish:'config.release.publish',rollback:'config.release.rollback'};return actions.filter(x=>this.hasPermission(permission[x]))}, actionLabel(a){return({validate:'校验',approve:'审批',gray:'开始灰度',publish:'全量发布',rollback:'回滚'})[a]},
    async doReleaseAction(row,action){try{const c=await this.riskPrompt(this.actionLabel(action));await api.releaseAction(row.id,action,row.version,c.reason,c.ticketNo);this.$message.success('发布状态已更新');this.load()}catch(e){this.notifyError(e)}},
    async saveAdmin(){try{const c=await this.riskPrompt('新增管理员');await api.createAdminAccount(this.adminForm,c.reason,c.ticketNo);this.adminDialog=false;this.adminForm={username:'',displayName:'',password:'',roleIds:[]};this.$message.success('管理员已创建');this.load()}catch(e){this.notifyError(e)}},
    async toggleAdmin(row){try{const c=await this.riskPrompt(row.status==='ACTIVE'?'停用管理员':'启用管理员');await api.changeAdminStatus(row.id,{status:row.status==='ACTIVE'?'DISABLED':'ACTIVE',expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('管理员状态已更新');this.load()}catch(e){this.notifyError(e)}},
    async resetAdminPwd(row){try{const pwd=await this.$prompt('请输入不少于 12 位的新密码','重置管理员密码',{inputType:'password',inputValidator:v=>!!(v&&v.length>=12)||'密码至少 12 位'});const c=await this.riskPrompt('重置管理员密码');await api.resetAdminPassword(row.id,{newPassword:pwd.value,expectedVersion:row.version},c.reason,c.ticketNo);this.$message.success('密码已重置');this.load()}catch(e){this.notifyError(e)}},
    editAdminRoles(row){this.selectionMode='adminRoles';this.selectionTarget=row;this.selectionTitle=`为 ${row.displayName} 分配角色`;this.selectionOptions=this.adminRoleOptions;this.selectedIds=row.roles.map(x=>x.id);this.selectionDialog=true},
    editRolePermissions(row){this.selectionMode='rolePermissions';this.selectionTarget=row;this.selectionTitle=`配置角色：${row.name}`;this.selectionOptions=this.adminPermissionOptions;this.selectedIds=row.permissions.map(x=>x.id);this.selectionDialog=true},
    async saveSelection(){try{const c=await this.riskPrompt('权限配置');if(this.selectionMode==='adminRoles')await api.assignAdminRoles(this.selectionTarget.id,{roleIds:this.selectedIds},c.reason,c.ticketNo);else await api.setAdminRolePermissions(this.selectionTarget.id,{permissionIds:this.selectedIds},c.reason,c.ticketNo);this.selectionDialog=false;this.$message.success('权限配置已更新');this.load()}catch(e){this.notifyError(e)}},
    async saveRole(){try{const c=await this.riskPrompt('新增角色');await api.createAdminRole(this.roleForm,c.reason,c.ticketNo);this.roleDialog=false;this.roleForm={roleKey:'',name:'',permissionIds:[]};this.$message.success('角色已创建');this.load()}catch(e){this.notifyError(e)}},
    notifyError(error){const message=error&&error.message?error.message:'操作失败，请检查输入或刷新后重试';this.$message.error(message)},
    formatPrice(p){return p?this.money(p.amountMinor,p.currency)+' / v'+p.versionNo:'未配置'},money(minor,currency){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:currency||'CNY'}).format((minor||0)/100)},percent(a,b){return b?Math.min(100,Math.round((a||0)*100/b)):0}
  }
}
</script>

<style lang="scss" scoped>
.companion-admin{min-height:calc(100vh - 84px);background:#f5f7fb}.page-heading{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:24px}.eyebrow{margin:0 0 6px;color:#2563eb;font-size:12px;font-weight:700;letter-spacing:1.6px}.page-heading h1{margin:0;color:#0f172a;font-size:30px}.description{margin:8px 0 0;color:#64748b}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.metric-card{padding:20px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.04)}.metric-card span,.metric-card small{display:block;color:#64748b}.metric-card strong{display:block;margin:10px 0 6px;color:#0f172a;font-size:28px}.section-row{margin-top:20px}.health-row{margin:18px 0}.health-row>div{display:flex;justify-content:space-between;margin-bottom:8px;color:#334155}.guard-card p{display:flex;gap:10px;align-items:flex-start;margin:16px 0;color:#475569;line-height:1.6}.guard-card i{margin-top:4px;color:#2563eb}.toolbar{display:flex;gap:12px;align-items:center;margin-bottom:18px}.toolbar .el-input,.toolbar .el-select,.filter-bar>.el-input,.filter-bar>.el-select{width:220px}.card-title{display:flex;justify-content:space-between;align-items:center}.pager{margin-top:20px;text-align:right}.danger{color:#dc2626!important}.role-tag{margin:2px 5px 2px 0}.permission-count{margin-right:10px;color:#64748b}.permission-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;max-height:360px;overflow:auto}.permission-grid .el-checkbox{display:flex!important;align-items:flex-start;margin:0!important;padding:10px;border:1px solid #e2e8f0;border-radius:8px}.permission-grid small{display:block;color:#94a3b8}.privacy-banner{display:flex;gap:14px;align-items:flex-start;margin-bottom:18px;padding:16px 18px;border:1px solid #bfdbfe;border-radius:10px;background:#eff6ff;color:#1e3a8a}.privacy-banner i{margin-top:3px;font-size:22px}.privacy-banner p{margin:5px 0 0;color:#475569}.dialog-form{margin-top:18px}@media(max-width:1000px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.metric-grid,.permission-grid{grid-template-columns:1fr}.page-heading{gap:12px}.toolbar{flex-wrap:wrap}}
</style>
