package com.lingxi.content.infrastructure.persistence;

import com.lingxi.content.api.TemplateGovernanceFacade.*;import com.lingxi.content.domain.TemplateGovernanceRepository;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;

@Repository
public class JdbcTemplateGovernanceRepository implements TemplateGovernanceRepository {
  private final JdbcTemplate jdbc;public JdbcTemplateGovernanceRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
  @Override public ReviewResult review(long id,long admin,long template,long version,String dimension,String decision,String comment,LocalDateTime now){jdbc.update("INSERT INTO content_template_review(id,template_id,template_version,review_dimension,decision,comment,reviewer_admin_id,created_at) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE decision=VALUES(decision),comment=VALUES(comment),reviewer_admin_id=VALUES(reviewer_admin_id),created_at=VALUES(created_at)",id,template,version,dimension,decision,comment,admin,now);return jdbc.query("SELECT * FROM content_template_review WHERE template_id=? AND template_version=? AND review_dimension=?",(r,n)->new ReviewResult(r.getLong("id"),r.getLong("template_id"),r.getLong("template_version"),r.getString("review_dimension"),r.getString("decision"),r.getString("comment"),r.getLong("reviewer_admin_id"),r.getObject("created_at",LocalDateTime.class)),template,version,dimension).stream().findFirst().orElseThrow();}
  @Override public List<ReviewResult> reviews(long template){return jdbc.query("SELECT * FROM content_template_review WHERE template_id=? ORDER BY template_version DESC,review_dimension",(r,n)->new ReviewResult(r.getLong("id"),r.getLong("template_id"),r.getLong("template_version"),r.getString("review_dimension"),r.getString("decision"),r.getString("comment"),r.getLong("reviewer_admin_id"),r.getObject("created_at",LocalDateTime.class)),template);}
  @Override public boolean allApproved(long template,long version){Integer n=jdbc.queryForObject("SELECT COUNT(DISTINCT review_dimension) FROM content_template_review WHERE template_id=? AND template_version=? AND decision='APPROVED' AND review_dimension IN ('SAFETY','FEASIBILITY','QUALITY')",Integer.class,template,version);return n!=null&&n==3;}
  @Override public List<MetricSummary> metrics(long template,LocalDate from,LocalDate to){return jdbc.query("SELECT metric_date,template_id,usage_count,completion_count,negative_feedback_count FROM content_template_metric_daily WHERE template_id=? AND metric_date BETWEEN ? AND ? ORDER BY metric_date",(r,n)->new MetricSummary(r.getObject("metric_date",LocalDate.class),r.getLong("template_id"),r.getLong("usage_count"),r.getLong("completion_count"),r.getLong("negative_feedback_count")),template,from,to);}
}
