import request from '@/utils/request'

export const adminLogin = data => request({ url: '/admin-api/v1/auth/login', method: 'post', headers: { isToken: false, repeatSubmit: false }, data })
export const adminProfile = () => request({ url: '/admin-api/v1/auth/profile', method: 'get' })
export const adminReauthenticate = password => request({ url: '/admin-api/v1/auth/reauthenticate', method: 'post', data: { password }, headers: { repeatSubmit: false } })
export const adminLogout = () => request({ url: '/admin-api/v1/auth/logout', method: 'delete' })
export const dashboard = () => request({ url: '/admin-api/v1/dashboard', method: 'get' })
export const users = params => request({ url: '/admin-api/v1/users', method: 'get', params })
export const changeUserStatus = (id, data, reason, ticketNo) => request({
  url: `/admin-api/v1/users/${id}/status`, method: 'put', data,
  headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo, repeatSubmit: false }
})
export const userDetail = id => request({ url: `/admin-api/v1/identity-governance/users/${id}`, method: 'get' })
export const loginRisks = params => request({ url: '/admin-api/v1/identity-governance/login-risks', method: 'get', params })
export const resolveLoginRisk = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/identity-governance/login-risks/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const ageAppeals = params => request({ url: '/admin-api/v1/identity-governance/age-appeals', method: 'get', params })
export const reviewAgeAppeal = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/identity-governance/age-appeals/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const privacyRequests = params => request({ url: '/admin-api/v1/identity-governance/privacy-requests', method: 'get', params })
export const guardianDisputes = params => request({ url: '/admin-api/v1/guardian-disputes', method: 'get', params })
export const resolveGuardianDispute = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/guardian-disputes/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const templates = params => request({ url: '/admin-api/v1/templates', method: 'get', params })
export const createTemplate = data => request({ url: '/admin-api/v1/templates', method: 'post', data })
export const templateAction = (id, action, data, reason, ticketNo) => request({ url: `/admin-api/v1/templates/${id}/${action}`, method: 'post', data, headers: reason ? { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo, repeatSubmit: false } : undefined })
export const templateReviews = id => request({ url: `/admin-api/v1/templates/${id}/reviews`, method: 'get' })
export const saveTemplateReview = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/templates/${id}/reviews`, method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const templateMetrics = (id, params) => request({ url: `/admin-api/v1/templates/${id}/metrics`, method: 'get', params })
export const commerceOverview = () => request({ url: '/admin-api/v1/commerce/overview', method: 'get' })
export const products = () => request({ url: '/admin-api/v1/commerce/products', method: 'get' })
export const orders = params => request({ url: '/admin-api/v1/commerce/orders', method: 'get', params })
export const subscriptions = params => request({ url: '/admin-api/v1/commerce/subscriptions', method: 'get', params })
export const entitlements = params => request({ url: '/admin-api/v1/commerce/entitlements', method: 'get', params })
export const saveProduct = (data, reason, ticketNo) => request({ url: '/admin-api/v1/commerce/manage/products', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const savePrice = (data, reason, ticketNo) => request({ url: '/admin-api/v1/commerce/manage/prices', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const promotions = params => request({ url: '/admin-api/v1/commerce/manage/promotions', method: 'get', params })
export const savePromotion = (data, reason, ticketNo) => request({ url: '/admin-api/v1/commerce/manage/promotions', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const confirmRefund = (data, reason, ticketNo) => request({ url: '/admin-api/v1/commerce/manage/refunds/confirm', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const adjustEntitlement = (data, reason, ticketNo) => request({ url: '/admin-api/v1/commerce/manage/entitlements/adjust', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const reconciliationCases = params => request({ url: '/admin-api/v1/commerce/manage/reconciliation-cases', method: 'get', params })
export const resolveReconciliation = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/commerce/manage/reconciliation-cases/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const tickets = params => request({ url: '/admin-api/v1/support-tickets', method: 'get', params })
export const ticketDetail = id => request({ url: `/admin-api/v1/support-tickets/${id}`, method: 'get' })
export const replyTicket = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/governance/support-tickets/${id}/messages`, method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const transitionTicket = (id, data, reason, ticketNo) => request({
  url: `/admin-api/v1/support-tickets/${id}`, method: 'put', data,
  headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo, repeatSubmit: false }
})
export const releases = params => request({ url: '/admin-api/v1/config-releases', method: 'get', params })
export const createRelease = (data, reason, ticketNo) => request({
  url: '/admin-api/v1/config-releases', method: 'post', data,
  headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo, repeatSubmit: false }
})
export const releaseAction = (id, action, expectedVersion, reason, ticketNo) => request({
  url: `/admin-api/v1/config-releases/${id}/${action}`, method: 'post', data: { expectedVersion },
  headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo, repeatSubmit: false }
})
export const audits = params => request({ url: '/admin-api/v1/audit-logs', method: 'get', params })
export const safetyCases = params => request({ url: '/admin-api/v1/safety-cases', method: 'get', params })
export const safetyAlerts = params => request({ url: '/admin-api/v1/safety-alerts', method: 'get', params })
export const transitionSafetyCase = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/safety-cases/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const transitionSafetyAlert = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/safety-alerts/${id}`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const governanceResources = params => request({ url: '/admin-api/v1/governance-resources', method: 'get', params })
const governanceWrite = (path, data, reason, ticketNo) => request({ url: `/admin-api/v1/governance/${path}`, method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const saveCampaign = (data, reason, ticketNo) => governanceWrite('campaigns', data, reason, ticketNo)
export const saveAppRelease = (data, reason, ticketNo) => governanceWrite('app-releases', data, reason, ticketNo)
export const saveComplianceDocument = (data, reason, ticketNo) => governanceWrite('compliance-documents', data, reason, ticketNo)
export const saveFeatureFlag = (data, reason, ticketNo) => governanceWrite('feature-flags', data, reason, ticketNo)
export const saveExperiment = (data, reason, ticketNo) => governanceWrite('experiments', data, reason, ticketNo)
export const retireGovernanceResource = (type, id, expectedVersion, reason, ticketNo) => request({ url: `/admin-api/v1/governance/${type}/${id}`, method: 'delete', params: { expectedVersion }, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const changeGovernanceRuntimeStatus = (type, id, data, reason, ticketNo) => request({ url: `/admin-api/v1/governance/${type}/${id}/runtime-status`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const analyticsMetrics = params => request({ url: '/admin-api/v1/analytics/metrics', method: 'get', params })
export const adminAccounts = () => request({ url: '/admin-api/v1/admin-management/admins', method: 'get' })
export const adminRoles = () => request({ url: '/admin-api/v1/admin-management/roles', method: 'get' })
export const adminPermissions = () => request({ url: '/admin-api/v1/admin-management/permissions', method: 'get' })
export const createAdminAccount = (data, reason, ticketNo) => request({ url: '/admin-api/v1/admin-management/admins', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const changeAdminStatus = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/admin-management/admins/${id}/status`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const resetAdminPassword = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/admin-management/admins/${id}/password`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const assignAdminRoles = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/admin-management/admins/${id}/roles`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const createAdminRole = (data, reason, ticketNo) => request({ url: '/admin-api/v1/admin-management/roles', method: 'post', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
export const setAdminRolePermissions = (id, data, reason, ticketNo) => request({ url: `/admin-api/v1/admin-management/roles/${id}/permissions`, method: 'put', data, headers: { 'X-Operation-Reason': reason, 'X-Ticket-No': ticketNo } })
