package com.lingxi.content.application;

import com.lingxi.content.api.TemplateGovernanceFacade;import com.lingxi.content.api.TemplateGovernanceFacade.*;import com.lingxi.content.domain.*;import com.lingxi.identity.api.*;import com.lingxi.kernel.*;
import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class TemplateGovernanceApplicationService implements TemplateGovernanceFacade {
  private final TemplateGovernanceRepository governance;private final ContentRepository content;private final ContentAdminAuthorizationAdapter admins;private final IdGenerator ids;private final DomainEventPublisher events;
  public TemplateGovernanceApplicationService(TemplateGovernanceRepository governance,ContentRepository content,List<ContentAdminAuthorizationAdapter> admins,IdGenerator ids,DomainEventPublisher events){this.governance=governance;this.content=content;this.admins=admins.stream().findFirst().orElse(null);this.ids=ids;this.events=events;}
  @Override @Transactional public ReviewResult reviewDimension(ReviewCommand c){require(c.adminId(),"content:template:quality");context(c.context());if(!Set.of("SAFETY","FEASIBILITY","QUALITY").contains(c.dimension())||!Set.of("APPROVED","REJECTED").contains(c.decision())||blank(c.comment()))invalid("模板评审参数不合法");TemplateVersion v=content.findTemplateVersion(c.templateVersionId()).orElseThrow(()->new BusinessException("CONTENT_TEMPLATE_NOT_FOUND","模板版本不存在"));if(v.getStatus()!=TemplateVersion.Status.REVIEWING||v.getVersion()!=c.expectedTemplateVersion())throw new BusinessException("CONTENT_TEMPLATE_CONFLICT","模板版本状态已变化");ReviewResult r=governance.review(ids.nextId(),c.adminId(),v.getId(),v.getVersion(),c.dimension(),c.decision(),c.comment(),now());events.publish(new AdminActionAuditedEvent(UUID.randomUUID().toString(),c.adminId(),"TEMPLATE_DIMENSION_REVIEW","TEMPLATE_VERSION",String.valueOf(v.getId()),v.getVersion(),c.context().reason(),c.context().ticketNo(),Instant.now()));return r;}
  @Override @Transactional(readOnly=true) public List<ReviewResult> reviews(long admin,long id){require(admin,"content:template:read");return governance.reviews(id);}
  @Override @Transactional(readOnly=true) public List<MetricSummary> metrics(long admin,long id,LocalDate from,LocalDate to){require(admin,"content:template:read");LocalDate end=to==null?LocalDate.now(ZoneOffset.UTC):to;LocalDate start=from==null?end.minusDays(29):from;if(end.isBefore(start))invalid("指标日期范围不合法");return governance.metrics(id,start,end);}
  public boolean allApproved(long id,long version){return governance.allApproved(id,version);}
  private void require(long admin,String permission){if(admins==null||!admins.allowed(admin,permission))throw new BusinessException("CONTENT_ADMIN_FORBIDDEN","管理员权限不足");}private void context(OperationContext c){if(c==null||!c.recentAuthentication()||blank(c.reason())||blank(c.ticketNo()))throw new BusinessException("CONTENT_HIGH_RISK_CONTEXT_REQUIRED","模板评审需要近期认证、原因和工单号");}private boolean blank(String v){return v==null||v.isBlank();}private void invalid(String m){throw new BusinessException("CONTENT_TEMPLATE_GOVERNANCE_INVALID",m);}private LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC);}
}
