# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/cloud
# 创建目录
RUN mkdir -p /home/cloud
# 指定路径
WORKDIR /home/cloud
# 复制jar文件到路径
COPY ./jar/cloud-modules-system.jar /home/cloud/cloud-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","cloud-modules-system.jar"]