package com.lingxi.identity.infrastructure.persistence;

import com.lingxi.identity.api.AdminIdentityGovernanceFacade.*;
import com.lingxi.identity.api.AdminUserFacade;
import com.lingxi.identity.domain.IdentityGovernanceRepository;
import com.lingxi.kernel.BusinessException;
import com.lingxi.kernel.PageResult;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

/** 身份治理事实表仓储，详情查询不跨模块联表。 */
@Repository
public class JdbcIdentityGovernanceRepository implements IdentityGovernanceRepository {
  private final JdbcTemplate jdbc;public JdbcIdentityGovernanceRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
  @Override public AdminUserFacade.AdminUserSummary user(long userId){return jdbc.query("SELECT id,public_id,age_band,status,timezone,authorization_version,version,created_at,updated_at FROM id_user WHERE id=? AND deleted=0",(r,n)->new AdminUserFacade.AdminUserSummary(r.getLong("id"),r.getString("public_id"),r.getString("age_band"),r.getString("status"),r.getString("timezone"),r.getLong("authorization_version"),r.getLong("version"),time(r,"created_at"),time(r,"updated_at")),userId).stream().findFirst().orElse(null);}
  @Override public List<DeviceSummary> devices(long userId){return jdbc.query("SELECT id,device_id,first_seen_at,last_seen_at FROM id_device WHERE user_id=? AND deleted=0 ORDER BY last_seen_at DESC",(r,n)->new DeviceSummary(r.getLong("id"),r.getString("device_id"),time(r,"first_seen_at"),time(r,"last_seen_at")),userId);}
  @Override public List<AgeVerificationSummary> ageVerifications(long userId){return jdbc.query("SELECT id,method,verified_birth_date,result,verified_at FROM id_age_verification WHERE user_id=? AND deleted=0 ORDER BY verified_at DESC",(r,n)->new AgeVerificationSummary(r.getLong("id"),r.getString("method"),r.getObject("verified_birth_date",LocalDate.class),r.getString("result"),time(r,"verified_at")),userId);}
  @Override public PageResult<LoginRiskSummary> loginRisks(String status,String level,int page,int size){List<Object>a=new ArrayList<>();String w=" WHERE deleted=0";if(text(status)){w+=" AND status=?";a.add(status);}if(text(level)){w+=" AND risk_level=?";a.add(level);}long total=count("id_login_risk_event",w,a);a.add(size);a.add((page-1)*size);List<LoginRiskSummary>items=jdbc.query("SELECT * FROM id_login_risk_event"+w+" ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->risk(r),a.toArray());return new PageResult<>(items,total,page,size);}
  @Override public LoginRiskSummary resolveLoginRisk(long admin,long id,String status,String resolution,long expected,LocalDateTime now){updated(jdbc.update("UPDATE id_login_risk_event SET status=?,reviewer_admin_id=?,resolution=?,version=version+1,updated_at=? WHERE id=? AND version=? AND deleted=0",status,admin,resolution,now,id,expected));return jdbc.query("SELECT * FROM id_login_risk_event WHERE id=? AND deleted=0",(r,n)->risk(r),id).stream().findFirst().orElseThrow();}
  @Override public PageResult<AgeAppealSummary> ageAppeals(String status,int page,int size){List<Object>a=new ArrayList<>();String w=" WHERE deleted=0";if(text(status)){w+=" AND status=?";a.add(status);}long total=count("id_age_appeal",w,a);a.add(size);a.add((page-1)*size);List<AgeAppealSummary>items=jdbc.query("SELECT * FROM id_age_appeal"+w+" ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->appeal(r),a.toArray());return new PageResult<>(items,total,page,size);}
  @Override public AgeAppealSummary findAgeAppeal(long id){return jdbc.query("SELECT * FROM id_age_appeal WHERE id=? AND deleted=0",(r,n)->appeal(r),id).stream().findFirst().orElse(null);}
  @Override public boolean hasPendingAgeAppeal(long userId){Integer value=jdbc.queryForObject("SELECT COUNT(*) FROM id_age_appeal WHERE user_id=? AND status='PENDING' AND deleted=0",Integer.class,userId);return value!=null&&value>0;}
  @Override public AgeAppealSummary insertAgeAppeal(long id,String no,long user,LocalDate birth,String evidence,LocalDateTime now){jdbc.update("INSERT INTO id_age_appeal(id,appeal_no,user_id,claimed_birth_date,evidence_ref,status,version,deleted,created_at,updated_at) VALUES(?,?,?,?,?,'PENDING',0,0,?,?)",id,no,user,birth,evidence,now,now);return findAgeAppeal(id);}
  @Override public AgeAppealSummary reviewAgeAppeal(long admin,long verificationId,long id,boolean approved,String resolution,long expected,LocalDateTime now){AgeAppealSummary a=findAgeAppeal(id);if(a==null)throw new BusinessException("IDENTITY_AGE_APPEAL_NOT_FOUND","年龄申诉不存在");String status=approved?"APPROVED":"REJECTED";updated(jdbc.update("UPDATE id_age_appeal SET status=?,reviewer_admin_id=?,resolution=?,version=version+1,updated_at=? WHERE id=? AND version=? AND status='PENDING' AND deleted=0",status,admin,resolution,now,id,expected));if(approved){LocalDate adultDate=a.claimedBirthDate().plusYears(18);String band=!LocalDate.now(ZoneOffset.UTC).isBefore(adultDate)?"ADULT":"TEEN";
    // 年龄申诉只确认年龄事实；青少年必须重新经过监护关系激活流程。
    String account="ADULT".equals(band)?"ACTIVE_ADULT":"PENDING_GUARDIAN";jdbc.update("INSERT INTO id_age_verification(id,user_id,method,evidence_reference,verified_birth_date,result,verified_at,created_at,deleted) VALUES(?,?,'ADMIN_APPEAL',?,?,'VERIFIED',?,?,0)",verificationId,a.userId(),a.evidenceRef(),a.claimedBirthDate(),now,now);updated(jdbc.update("UPDATE id_user SET age_band=?,status=?,adult_transition_date=?,authorization_version=authorization_version+1,version=version+1,updated_at=? WHERE id=? AND deleted=0 AND status NOT IN ('CLOSING','CLOSED')",band,account,adultDate,now,a.userId()));}return findAgeAppeal(id);}
  @Override public PageResult<PrivacyRequestSummary> privacyRequests(String status,int page,int size){List<Object>a=new ArrayList<>();String w=" WHERE 1=1";if(text(status)){w+=" AND status=?";a.add(status);}long total=count("id_privacy_request",w,a);a.add(size);a.add((page-1)*size);List<PrivacyRequestSummary>items=jdbc.query("SELECT * FROM id_privacy_request"+w+" ORDER BY deadline ASC LIMIT ? OFFSET ?",(r,n)->new PrivacyRequestSummary(r.getLong("id"),r.getLong("user_id"),r.getString("type"),r.getString("status"),r.getInt("progress"),time(r,"deadline"),r.getString("result_reference"),r.getString("last_error"),r.getLong("version"),time(r,"created_at"),time(r,"updated_at")),a.toArray());return new PageResult<>(items,total,page,size);}
  private LoginRiskSummary risk(ResultSet r)throws SQLException{long reviewer=r.getLong("reviewer_admin_id");boolean noReviewer=r.wasNull();return new LoginRiskSummary(r.getLong("id"),r.getLong("user_id"),r.getString("device_id"),r.getString("risk_level"),r.getString("risk_type"),r.getString("summary"),r.getString("status"),noReviewer?null:reviewer,r.getString("resolution"),r.getLong("version"),time(r,"created_at"),time(r,"updated_at"));}
  private AgeAppealSummary appeal(ResultSet r)throws SQLException{long reviewer=r.getLong("reviewer_admin_id");boolean noReviewer=r.wasNull();return new AgeAppealSummary(r.getLong("id"),r.getString("appeal_no"),r.getLong("user_id"),r.getObject("claimed_birth_date",LocalDate.class),r.getString("evidence_ref"),r.getString("status"),noReviewer?null:reviewer,r.getString("resolution"),r.getLong("version"),time(r,"created_at"),time(r,"updated_at"));}
  private LocalDateTime time(ResultSet r,String c)throws SQLException{return r.getObject(c,LocalDateTime.class);}private boolean text(String v){return v!=null&&!v.isBlank();}private long count(String t,String w,List<Object>a){Long v=jdbc.queryForObject("SELECT COUNT(*) FROM "+t+w,Long.class,a.toArray());return v==null?0:v;}private void updated(int n){if(n!=1)throw new BusinessException("IDENTITY_GOVERNANCE_CONFLICT","治理记录已变化，请刷新后重试");}
}
