# 基础镜像
FROM nginx
# author
MAINTAINER cloud

# 挂载目录
VOLUME /home/cloud/projects/cloud-ui
# 创建目录
RUN mkdir -p /home/cloud/projects/cloud-ui
# 指定路径
WORKDIR /home/cloud/projects/cloud-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/cloud/projects/cloud-ui
