# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER cloud

# 挂载目录
VOLUME /home/cloud
# 创建目录
RUN mkdir -p /home/cloud
# 指定路径
WORKDIR /home/cloud
# 复制jar文件到路径
COPY ./jar/cloud-gateway.jar /home/cloud/cloud-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","cloud-gateway.jar"]