package com.lingxi.relationship.application;

import com.lingxi.identity.api.*;import com.lingxi.kernel.*;import com.lingxi.relationship.api.GuardianDisputeFacade;import com.lingxi.relationship.api.GuardianDisputeFacade.*;import com.lingxi.relationship.domain.GuardianDisputeRepository;
import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class GuardianDisputeApplicationService implements GuardianDisputeFacade {
  private final GuardianDisputeRepository repository;private final AdminAuthorizationFacade admins;private final IdGenerator ids;private final DomainEventPublisher events;
  public GuardianDisputeApplicationService(GuardianDisputeRepository repository,AdminAuthorizationFacade admins,IdGenerator ids,DomainEventPublisher events){this.repository=repository;this.admins=admins;this.ids=ids;this.events=events;}
  @Override @Transactional public DisputeSummary submit(long userId,SubmitDisputeCommand c){if(c==null||c.relationId()<=0||blank(c.reason()))invalid("监护争议参数不完整");GuardianDisputeRepository.RelationParties p=repository.relationParties(c.relationId());if(p==null||p.guardianUserId()==null)throw new BusinessException("REL_GUARDIAN_RELATION_NOT_FOUND","监护关系不存在");if(userId!=p.teenUserId()&&userId!=p.guardianUserId())throw new BusinessException("REL_GUARDIAN_DISPUTE_FORBIDDEN","无权对该监护关系发起争议");if(repository.hasOpenDispute(c.relationId()))throw new BusinessException("REL_GUARDIAN_DISPUTE_PENDING","该监护关系已有待处理争议");long id=ids.nextId();return repository.insert(id,"GD"+id,c.relationId(),p.teenUserId(),p.guardianUserId(),c.reason().trim(),now());}
  @Override @Transactional(readOnly=true) public PageResult<DisputeSummary> list(long admin,String status,int page,int size){require(admin);return repository.list(status,Math.max(1,page),Math.min(100,Math.max(1,size)));}
  @Override @Transactional public DisputeSummary resolve(ResolveDisputeCommand c){require(c.adminId());context(c.context());if(!Set.of("REVIEWING","RESOLVED","DISMISSED").contains(c.status())||blank(c.resolution()))invalid("监护争议处置参数不合法");DisputeSummary r=repository.resolve(c.adminId(),c.id(),c.status(),c.resolution(),c.expectedVersion(),now());events.publish(new AdminActionAuditedEvent(UUID.randomUUID().toString(),c.adminId(),"GUARDIAN_DISPUTE_RESOLVE","GUARDIAN_DISPUTE",String.valueOf(r.id()),r.version(),c.context().reason(),c.context().ticketNo(),Instant.now()));return r;}
  private void require(long admin){if(!admins.allowed(admin,"relationship:guardian-dispute:manage"))throw new BusinessException("ADMIN_FORBIDDEN","管理员权限不足");}private void context(OperationContext c){if(c==null||!c.recentAuthentication()||blank(c.reason())||blank(c.ticketNo()))throw new BusinessException("ADMIN_HIGH_RISK_CONTEXT_REQUIRED","操作需要近期认证、具体原因和工单号");}private boolean blank(String v){return v==null||v.isBlank();}private void invalid(String m){throw new BusinessException("REL_GUARDIAN_DISPUTE_INVALID",m);}private LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC);}
}
